### PR TITLE
Rename of exclude_vertebrates.ini to include_vertebrates.ini and list…

### PR DESCRIPTION
**Pull request by fergalmartin**
… update

Added in all the production names for the species to include in BioMart, this reverses the previous list (which was all the species to exclude) and to reflect this the name has been changed. The list has been updated to include the two dog breeds that were missing from e99 and also contains the renamed version of the dog reference production name (canis_lupis_familiaris)

### CODE REVIEW

**Comment by thomasmaurel** [comment]
@fergalmartin: I've noticed that this list only contains the release 99 species. Do you want any new species from 100 in the gene mart this release?

**Comment by fergalmartin** [comment]
@thomasmaurel There is nothing critically important that has been added, so I was planning on just leaving as and seeing if there are any requests after it releases. If we want to add anything then I would need to go back to the list and decide what to remove and it takes a bit of time to do that, so I am assuming that you would like to start building asap.

**Comment by thomasmaurel** [comment]
@fergalmartin: Thank you, no worries then. We can't start the mart right now but I want to make the code update asap.

**Comment by thomasmaurel** [comment]
Mart code changes to support the new list will be in the next PR.

**Pull request merged**
